/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../studio/schema.json
export type ProductImage = {
  _type: "productImage";
  product?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "product";
  };
  size?: "small" | "medium" | "large";
  alignment?: "left" | "center" | "right";
  showLink?: boolean;
  caption?: string;
  altText?: string;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
};

export type Link = {
  _type: "link";
  linkType?: "href" | "page" | "post";
  href?: string;
  page?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  openInNewTab?: boolean;
};

export type CallToAction = {
  _type: "callToAction";
  heading?: string;
  text?: string;
  buttonText?: string;
  link?: Link;
};

export type InfoSection = {
  _type: "infoSection";
  heading?: string;
  subheading?: string;
  content?: BlockContent;
};

export type BlockContent = Array<{
  _key: string;
} & ProductImage | {
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    linkType?: "href" | "page" | "post";
    href?: string;
    page?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    post?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "post";
    };
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Scrape = {
  _id: string;
  _type: "scrape";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  product?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "product";
  };
  scrapedAt?: string;
  source?: string;
  title?: string;
  brand?: string;
  images?: Array<string>;
  bestSellerBadge?: boolean;
  price?: {
    amount?: number;
    currency?: "USD" | "EUR" | "GBP";
  };
  availability?: "inStock" | "outOfStock" | "backorder" | "discontinued";
  delivery?: {
    type?: string;
    date?: string;
    cost?: number;
  };
  seller?: {
    name?: string;
    isAmazonFulfilled?: boolean;
    sellerId?: string;
  };
  deal?: {
    hasDeal?: boolean;
    dealType?: string;
    discountPercentage?: number;
    dealEndDate?: string;
    couponCode?: string;
  };
  rating?: {
    average?: number;
    count?: number;
  };
  features?: Array<string>;
  specifications?: {
    items?: Array<{
      label?: string;
      value?: string;
      _key: string;
    }>;
  };
  rawData?: string;
  notes?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  heading?: string;
  subheading?: string;
  pageBuilder?: Array<{
    _key: string;
  } & CallToAction | {
    _key: string;
  } & InfoSection>;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: BlockContent;
  excerpt?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  date?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "person";
  };
  postType?: "general" | "productReview" | "comparison";
  product?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "product";
  };
  products?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
  scrapes?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "scrape";
  }>;
  featured?: boolean;
  affiliateDisclosure?: string;
  callToAction?: {
    text?: string;
    link?: string;
  };
  metaTitle?: string;
  metaDescription?: string;
  focusKeyword?: string;
  relatedKeywords?: Array<string>;
  noIndex?: boolean;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  asin?: string;
  approvalStatus?: "pending" | "approved" | "rejected" | "paused";
  brand?: string;
  discoveryImage?: string;
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  affiliateUrl?: string;
  scrapes?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "scrape";
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  metaDescription?: string;
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  icon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  parentCategory?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  searchFocus?: string;
  targetProductCount?: number;
  discoveryStatus?: "active" | "paused" | "completed";
  discoveryPriority?: number;
  lastDiscoveryAt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  picture?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  url?: string;
  copyright?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  logoalt?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  email?: string;
  phone?: string;
  w3ckey?: string;
  social?: Array<{
    media?: "twitter" | "facebook" | "instagram" | "linkedin" | "youtube";
    url?: string;
    _key: string;
  }>;
  description?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    metadataBase?: string;
    _type: "image";
  };
  twitterHandle?: string;
  googleVerification?: string;
  siteKeywords?: Array<string>;
  activeTheme?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "theme";
  };
  affiliateDisclosure?: string;
  amazonAssociateTag?: string;
  ctaButtonText?: string;
  showPriceRange?: boolean;
  trustBadges?: Array<{
    label?: string;
    icon?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    description?: string;
    _key: string;
  }>;
};

export type Theme = {
  _id: string;
  _type: "theme";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  primaryColor?: Color;
  secondaryColor?: Color;
  accentColor?: Color;
  neutralColor?: Color;
  headingFont?: "Inter" | "Lora" | "Roboto" | "Playfair Display" | "Montserrat" | "Merriweather";
  bodyFont?: "Inter" | "Lora" | "Roboto" | "Source Sans Pro" | "Open Sans" | "Nunito Sans";
  fontSize?: {
    base?: "14px" | "16px" | "18px";
    scale?: number;
  };
  borderRadius?: "none" | "sm" | "md" | "lg" | "xl" | "full";
  spacing?: {
    containerWidth?: "1024px" | "1200px" | "1400px" | "1600px";
    sectionSpacing?: "1.5rem" | "2rem" | "3rem" | "4rem";
  };
  buttonStyle?: "rounded" | "square" | "pill";
  cardStyle?: "flat" | "shadow" | "border" | "elevated";
  navbarStyle?: "transparent" | "solid" | "blur";
  description?: string;
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<{
    _key: string;
  } & SanityAssistInstructionTask>;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<{
    _key: string;
  } & SanityAssistSchemaTypeField>;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "assist.instruction.context";
  };
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message?: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  } | {
    _key: string;
  } & SanityAssistInstructionFieldRef | {
    _key: string;
  } & SanityAssistInstructionContext | {
    _key: string;
  } & SanityAssistInstructionUserInput>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<{
    _key: string;
  } & SanityAssistOutputField | {
    _key: string;
  } & SanityAssistOutputType>;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<{
    _key: string;
  } & SanityAssistInstruction>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = ProductImage | Color | Link | CallToAction | InfoSection | BlockContent | Scrape | Page | Post | Product | Category | SanityImageCrop | SanityImageHotspot | Slug | Person | Settings | Theme | SanityAssistInstructionTask | SanityAssistTaskStatus | SanityAssistSchemaTypeAnnotations | SanityAssistOutputType | SanityAssistOutputField | SanityAssistInstructionContext | AssistInstructionContext | SanityAssistInstructionUserInput | SanityAssistInstructionPrompt | SanityAssistInstructionFieldRef | SanityAssistInstruction | SanityAssistSchemaTypeField | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: lib/sanity/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]{  ...,  activeTheme->{    _id,    title,    slug,    primaryColor,    secondaryColor,    accentColor,    neutralColor,    headingFont,    bodyFont,    fontSize,    borderRadius,    spacing,    buttonStyle,    cardStyle,    navbarStyle,    description  },  affiliateDisclosure,  amazonAssociateTag,  ctaButtonText,  showPriceRange,  trustBadges,  twitterHandle,  googleVerification,  siteKeywords}
export type SettingsQueryResult = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  url?: string;
  copyright?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  logoalt?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  email?: string;
  phone?: string;
  w3ckey?: string;
  social?: Array<{
    media?: "facebook" | "instagram" | "linkedin" | "twitter" | "youtube";
    url?: string;
    _key: string;
  }>;
  description?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    metadataBase?: string;
    _type: "image";
  };
  twitterHandle: string | null;
  googleVerification: string | null;
  siteKeywords: Array<string> | null;
  activeTheme: {
    _id: string;
    title: string | null;
    slug: Slug | null;
    primaryColor: Color | null;
    secondaryColor: Color | null;
    accentColor: Color | null;
    neutralColor: Color | null;
    headingFont: "Inter" | "Lora" | "Merriweather" | "Montserrat" | "Playfair Display" | "Roboto" | null;
    bodyFont: "Inter" | "Lora" | "Nunito Sans" | "Open Sans" | "Roboto" | "Source Sans Pro" | null;
    fontSize: {
      base?: "14px" | "16px" | "18px";
      scale?: number;
    } | null;
    borderRadius: "full" | "lg" | "md" | "none" | "sm" | "xl" | null;
    spacing: {
      containerWidth?: "1024px" | "1200px" | "1400px" | "1600px";
      sectionSpacing?: "1.5rem" | "2rem" | "3rem" | "4rem";
    } | null;
    buttonStyle: "pill" | "rounded" | "square" | null;
    cardStyle: "border" | "elevated" | "flat" | "shadow" | null;
    navbarStyle: "blur" | "solid" | "transparent" | null;
    description: string | null;
  } | null;
  affiliateDisclosure: string | null;
  amazonAssociateTag: string | null;
  ctaButtonText: string | null;
  showPriceRange: boolean | null;
  trustBadges: Array<{
    label?: string;
    icon?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    description?: string;
    _key: string;
  }> | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: themeQuery
// Query: *[_type == "theme" && slug.current == $slug][0]{  _id,  title,  slug,  primaryColor,  secondaryColor,  accentColor,  neutralColor,  headingFont,  bodyFont,  fontSize,  borderRadius,  spacing,  buttonStyle,  cardStyle,  navbarStyle,  description}
export type ThemeQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  primaryColor: Color | null;
  secondaryColor: Color | null;
  accentColor: Color | null;
  neutralColor: Color | null;
  headingFont: "Inter" | "Lora" | "Merriweather" | "Montserrat" | "Playfair Display" | "Roboto" | null;
  bodyFont: "Inter" | "Lora" | "Nunito Sans" | "Open Sans" | "Roboto" | "Source Sans Pro" | null;
  fontSize: {
    base?: "14px" | "16px" | "18px";
    scale?: number;
  } | null;
  borderRadius: "full" | "lg" | "md" | "none" | "sm" | "xl" | null;
  spacing: {
    containerWidth?: "1024px" | "1200px" | "1400px" | "1600px";
    sectionSpacing?: "1.5rem" | "2rem" | "3rem" | "4rem";
  } | null;
  buttonStyle: "pill" | "rounded" | "square" | null;
  cardStyle: "border" | "elevated" | "flat" | "shadow" | null;
  navbarStyle: "blur" | "solid" | "transparent" | null;
  description: string | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{      ...,      _type == "callToAction" => {          link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      },      },      _type == "infoSection" => {        content[]{          ...,          markDefs[]{            ...,              _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }          }        }      },    },  }
export type GetPageQueryResult = {
  _id: string;
  _type: "page";
  name: string | null;
  slug: Slug | null;
  heading: string | null;
  subheading: string | null;
  pageBuilder: Array<{
    _key: string;
    _type: "callToAction";
    heading?: string;
    text?: string;
    buttonText?: string;
    link: {
      _type: "link";
      linkType?: "href" | "page" | "post";
      href?: string;
      page: string | null;
      post: string | null;
      openInNewTab?: boolean;
    } | null;
  } | {
    _key: string;
    _type: "infoSection";
    heading?: string;
    subheading?: string;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs: Array<{
        linkType?: "href" | "page" | "post";
        href?: string;
        page: string | null;
        post: string | null;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }> | null;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      _key: string;
      _type: "productImage";
      product?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "product";
      };
      size?: "large" | "medium" | "small";
      alignment?: "center" | "left" | "right";
      showLink?: boolean;
      caption?: string;
      altText?: string;
      markDefs: null;
    }> | null;
  }> | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: sitemapData
// Query: *[_type == "page" || _type == "post" && defined(slug.current) || _type == "category" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,    featured,    postType,  }
export type SitemapDataResult = Array<{
  slug: string | null;
  _type: "category";
  _updatedAt: string;
  featured: null;
  postType: null;
} | {
  slug: string | null;
  _type: "page";
  _updatedAt: string;
  featured: null;
  postType: null;
} | {
  slug: string | null;
  _type: "post";
  _updatedAt: string;
  featured: boolean | null;
  postType: "comparison" | "general" | "productReview" | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  _updatedAt,  "author": author->{    firstName,    lastName,    picture,    "preferredAiModel": preferredAiModel->{modelId, name}  },  postType,  featured,  affiliateDisclosure,  callToAction,  metaTitle,  metaDescription,  focusKeyword,  relatedKeywords,  noIndex,  "product": product->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },  "products": products[]->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },  }
export type AllPostsQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  _updatedAt: string;
  author: {
    firstName: string | null;
    lastName: string | null;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    preferredAiModel: null;
  } | null;
  postType: "comparison" | "general" | "productReview" | null;
  featured: boolean | null;
  affiliateDisclosure: string | null;
  callToAction: {
    text?: string;
    link?: string;
  } | null;
  metaTitle: string | null;
  metaDescription: string | null;
  focusKeyword: string | null;
  relatedKeywords: Array<string> | null;
  noIndex: boolean | null;
  product: {
    _id: string;
    name: string | null;
    asin: string | null;
    brand: string | null;
    paApiPrimaryImageUrl: null;
    paApiVariantImageUrls: null;
    paApiImageUpdatedAt: null;
    discoveryImage: string | null;
    category: {
      name: string | null;
      slug: string | null;
    } | null;
    latestScrapeImages: Array<string> | null;
  } | null;
  products: Array<{
    _id: string;
    name: string | null;
    asin: string | null;
    brand: string | null;
    paApiPrimaryImageUrl: null;
    paApiVariantImageUrls: null;
    paApiImageUpdatedAt: null;
    discoveryImage: string | null;
    category: {
      name: string | null;
      slug: string | null;
    } | null;
    latestScrapeImages: Array<string> | null;
  }> | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: morePostsQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  _updatedAt,  "author": author->{    firstName,    lastName,    picture,    "preferredAiModel": preferredAiModel->{modelId, name}  },  postType,  featured,  affiliateDisclosure,  callToAction,  metaTitle,  metaDescription,  focusKeyword,  relatedKeywords,  noIndex,  "product": product->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },  "products": products[]->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },  }
export type MorePostsQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  _updatedAt: string;
  author: {
    firstName: string | null;
    lastName: string | null;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    preferredAiModel: null;
  } | null;
  postType: "comparison" | "general" | "productReview" | null;
  featured: boolean | null;
  affiliateDisclosure: string | null;
  callToAction: {
    text?: string;
    link?: string;
  } | null;
  metaTitle: string | null;
  metaDescription: string | null;
  focusKeyword: string | null;
  relatedKeywords: Array<string> | null;
  noIndex: boolean | null;
  product: {
    _id: string;
    name: string | null;
    asin: string | null;
    brand: string | null;
    paApiPrimaryImageUrl: null;
    paApiVariantImageUrls: null;
    paApiImageUpdatedAt: null;
    discoveryImage: string | null;
    category: {
      name: string | null;
      slug: string | null;
    } | null;
    latestScrapeImages: Array<string> | null;
  } | null;
  products: Array<{
    _id: string;
    name: string | null;
    asin: string | null;
    brand: string | null;
    paApiPrimaryImageUrl: null;
    paApiVariantImageUrls: null;
    paApiImageUpdatedAt: null;
    discoveryImage: string | null;
    category: {
      name: string | null;
      slug: string | null;
    } | null;
    latestScrapeImages: Array<string> | null;
  }> | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {    content[]{      ...,      _type == "productImage" => {        ...,        product->{          _id,          name,          asin,          paApiPrimaryImageUrl,          paApiVariantImageUrls,          paApiImageUpdatedAt,          discoveryImage,          "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images        }      },      markDefs[]{        ...,          _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }    },      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  _updatedAt,  "author": author->{    firstName,    lastName,    picture,    "preferredAiModel": preferredAiModel->{modelId, name}  },  postType,  featured,  affiliateDisclosure,  callToAction,  metaTitle,  metaDescription,  focusKeyword,  relatedKeywords,  noIndex,  "product": product->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },  "products": products[]->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },  }
export type PostQueryResult = {
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      linkType?: "href" | "page" | "post";
      href?: string;
      page: string | null;
      post: string | null;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
    _type: "productImage";
    product: {
      _id: string;
      name: string | null;
      asin: string | null;
      paApiPrimaryImageUrl: null;
      paApiVariantImageUrls: null;
      paApiImageUpdatedAt: null;
      discoveryImage: string | null;
      latestScrapeImages: Array<string> | null;
    } | null;
    size?: "large" | "medium" | "small";
    alignment?: "center" | "left" | "right";
    showLink?: boolean;
    caption?: string;
    altText?: string;
    markDefs: null;
  }> | null;
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  _updatedAt: string;
  author: {
    firstName: string | null;
    lastName: string | null;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    preferredAiModel: null;
  } | null;
  postType: "comparison" | "general" | "productReview" | null;
  featured: boolean | null;
  affiliateDisclosure: string | null;
  callToAction: {
    text?: string;
    link?: string;
  } | null;
  metaTitle: string | null;
  metaDescription: string | null;
  focusKeyword: string | null;
  relatedKeywords: Array<string> | null;
  noIndex: boolean | null;
  product: {
    _id: string;
    name: string | null;
    asin: string | null;
    brand: string | null;
    paApiPrimaryImageUrl: null;
    paApiVariantImageUrls: null;
    paApiImageUpdatedAt: null;
    discoveryImage: string | null;
    category: {
      name: string | null;
      slug: string | null;
    } | null;
    latestScrapeImages: Array<string> | null;
  } | null;
  products: Array<{
    _id: string;
    name: string | null;
    asin: string | null;
    brand: string | null;
    paApiPrimaryImageUrl: null;
    paApiVariantImageUrls: null;
    paApiImageUpdatedAt: null;
    discoveryImage: string | null;
    category: {
      name: string | null;
      slug: string | null;
    } | null;
    latestScrapeImages: Array<string> | null;
  }> | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
  slug: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: productByASINQuery
// Query: *[_type == "product" && asin == $asin][0] {      _id,  name,  asin,  brand,  "category": category->{name, slug},  approvalStatus,  affiliateUrl  }
export type ProductByASINQueryResult = {
  _id: string;
  name: string | null;
  asin: string | null;
  brand: string | null;
  category: {
    name: string | null;
    slug: Slug | null;
  } | null;
  approvalStatus: "approved" | "paused" | "pending" | "rejected" | null;
  affiliateUrl: string | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: productsByCategoryQuery
// Query: *[_type == "product" && category._ref == $categoryId] | order(_updatedAt desc) {      _id,  name,  asin,  brand,  "category": category->{name, slug},  approvalStatus,  affiliateUrl  }
export type ProductsByCategoryQueryResult = Array<{
  _id: string;
  name: string | null;
  asin: string | null;
  brand: string | null;
  category: {
    name: string | null;
    slug: Slug | null;
  } | null;
  approvalStatus: "approved" | "paused" | "pending" | "rejected" | null;
  affiliateUrl: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: relatedProductsQuery
// Query: *[_type == "product" && _id != $skip && category._ref == $categoryId] | order(_updatedAt desc) [0...$limit] {      _id,  name,  asin,  brand,  "category": category->{name, slug},  approvalStatus,  affiliateUrl  }
export type RelatedProductsQueryResult = Array<{
  _id: string;
  name: string | null;
  asin: string | null;
  brand: string | null;
  category: {
    name: string | null;
    slug: Slug | null;
  } | null;
  approvalStatus: "approved" | "paused" | "pending" | "rejected" | null;
  affiliateUrl: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: categoriesQuery
// Query: *[_type == "category"] | order(name asc) {    _id,    name,    "slug": slug.current,    description,    icon,    "parentCategory": parentCategory->{name, "slug": slug.current}  }
export type CategoriesQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  icon: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  parentCategory: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: broadCategoriesQuery
// Query: *[_type == "category" && !defined(parentCategory)] | order(name asc) {    _id,    name,    "slug": slug.current,    description,    icon  }
export type BroadCategoriesQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  icon: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: subcategoriesByParentQuery
// Query: *[_type == "category" && parentCategory->slug.current == $parentSlug] | order(name asc) {    _id,    name,    "slug": slug.current,    "postCount": count(*[_type == "post" && (      product->category._ref == ^._id ||      ^._id in products[]->category._ref    )])  }
export type SubcategoriesByParentQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  postCount: number;
}>;

// Source: lib/sanity/queries.ts
// Variable: categoryBySlugQuery
// Query: *[_type == "category" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    description,    metaDescription,    featuredImage,    icon,    "parentCategory": parentCategory->{name, "slug": slug.current},    "isBroadCategory": !defined(parentCategory),    "posts": *[_type == "post" && category._ref == ^._id && defined(slug.current)] | order(date desc) {        _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  _updatedAt,  "author": author->{    firstName,    lastName,    picture,    "preferredAiModel": preferredAiModel->{modelId, name}  },  postType,  featured,  affiliateDisclosure,  callToAction,  metaTitle,  metaDescription,  focusKeyword,  relatedKeywords,  noIndex,  "product": product->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },  "products": products[]->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },    }  }
export type CategoryBySlugQueryResult = {
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  metaDescription: string | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  icon: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  parentCategory: {
    name: string | null;
    slug: string | null;
  } | null;
  isBroadCategory: false | true;
  posts: Array<never>;
} | null;

// Source: lib/sanity/queries.ts
// Variable: postsByParentCategoryQuery
// Query: *[_type == "post" && (    product->category->parentCategory->slug.current == $parentSlug ||    count(products[@->category->parentCategory->slug.current == $parentSlug]) > 0  ) && defined(slug.current)] | order(date desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  _updatedAt,  "author": author->{    firstName,    lastName,    picture,    "preferredAiModel": preferredAiModel->{modelId, name}  },  postType,  featured,  affiliateDisclosure,  callToAction,  metaTitle,  metaDescription,  focusKeyword,  relatedKeywords,  noIndex,  "product": product->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },  "products": products[]->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },  }
export type PostsByParentCategoryQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  _updatedAt: string;
  author: {
    firstName: string | null;
    lastName: string | null;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    preferredAiModel: null;
  } | null;
  postType: "comparison" | "general" | "productReview" | null;
  featured: boolean | null;
  affiliateDisclosure: string | null;
  callToAction: {
    text?: string;
    link?: string;
  } | null;
  metaTitle: string | null;
  metaDescription: string | null;
  focusKeyword: string | null;
  relatedKeywords: Array<string> | null;
  noIndex: boolean | null;
  product: {
    _id: string;
    name: string | null;
    asin: string | null;
    brand: string | null;
    paApiPrimaryImageUrl: null;
    paApiVariantImageUrls: null;
    paApiImageUpdatedAt: null;
    discoveryImage: string | null;
    category: {
      name: string | null;
      slug: string | null;
    } | null;
    latestScrapeImages: Array<string> | null;
  } | null;
  products: Array<{
    _id: string;
    name: string | null;
    asin: string | null;
    brand: string | null;
    paApiPrimaryImageUrl: null;
    paApiVariantImageUrls: null;
    paApiImageUpdatedAt: null;
    discoveryImage: string | null;
    category: {
      name: string | null;
      slug: string | null;
    } | null;
    latestScrapeImages: Array<string> | null;
  }> | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: categorySlugsQuery
// Query: *[_type == "category" && defined(slug.current)]  {"slug": slug.current}
export type CategorySlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: productReviewQuery
// Query: *[_type == "post" && postType == "productReview" && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  _updatedAt,  "author": author->{    firstName,    lastName,    picture,    "preferredAiModel": preferredAiModel->{modelId, name}  },  postType,  featured,  affiliateDisclosure,  callToAction,  metaTitle,  metaDescription,  focusKeyword,  relatedKeywords,  noIndex,  "product": product->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },  "products": products[]->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },  }
export type ProductReviewQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  _updatedAt: string;
  author: {
    firstName: string | null;
    lastName: string | null;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    preferredAiModel: null;
  } | null;
  postType: "comparison" | "general" | "productReview" | null;
  featured: boolean | null;
  affiliateDisclosure: string | null;
  callToAction: {
    text?: string;
    link?: string;
  } | null;
  metaTitle: string | null;
  metaDescription: string | null;
  focusKeyword: string | null;
  relatedKeywords: Array<string> | null;
  noIndex: boolean | null;
  product: {
    _id: string;
    name: string | null;
    asin: string | null;
    brand: string | null;
    paApiPrimaryImageUrl: null;
    paApiVariantImageUrls: null;
    paApiImageUpdatedAt: null;
    discoveryImage: string | null;
    category: {
      name: string | null;
      slug: string | null;
    } | null;
    latestScrapeImages: Array<string> | null;
  } | null;
  products: Array<{
    _id: string;
    name: string | null;
    asin: string | null;
    brand: string | null;
    paApiPrimaryImageUrl: null;
    paApiVariantImageUrls: null;
    paApiImageUpdatedAt: null;
    discoveryImage: string | null;
    category: {
      name: string | null;
      slug: string | null;
    } | null;
    latestScrapeImages: Array<string> | null;
  }> | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: comparisonQuery
// Query: *[_type == "post" && postType == "comparison" && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  _updatedAt,  "author": author->{    firstName,    lastName,    picture,    "preferredAiModel": preferredAiModel->{modelId, name}  },  postType,  featured,  affiliateDisclosure,  callToAction,  metaTitle,  metaDescription,  focusKeyword,  relatedKeywords,  noIndex,  "product": product->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },  "products": products[]->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },  }
export type ComparisonQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  _updatedAt: string;
  author: {
    firstName: string | null;
    lastName: string | null;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    preferredAiModel: null;
  } | null;
  postType: "comparison" | "general" | "productReview" | null;
  featured: boolean | null;
  affiliateDisclosure: string | null;
  callToAction: {
    text?: string;
    link?: string;
  } | null;
  metaTitle: string | null;
  metaDescription: string | null;
  focusKeyword: string | null;
  relatedKeywords: Array<string> | null;
  noIndex: boolean | null;
  product: {
    _id: string;
    name: string | null;
    asin: string | null;
    brand: string | null;
    paApiPrimaryImageUrl: null;
    paApiVariantImageUrls: null;
    paApiImageUpdatedAt: null;
    discoveryImage: string | null;
    category: {
      name: string | null;
      slug: string | null;
    } | null;
    latestScrapeImages: Array<string> | null;
  } | null;
  products: Array<{
    _id: string;
    name: string | null;
    asin: string | null;
    brand: string | null;
    paApiPrimaryImageUrl: null;
    paApiVariantImageUrls: null;
    paApiImageUpdatedAt: null;
    discoveryImage: string | null;
    category: {
      name: string | null;
      slug: string | null;
    } | null;
    latestScrapeImages: Array<string> | null;
  }> | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: featuredPostsQuery
// Query: *[_type == "post" && featured == true && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  _updatedAt,  "author": author->{    firstName,    lastName,    picture,    "preferredAiModel": preferredAiModel->{modelId, name}  },  postType,  featured,  affiliateDisclosure,  callToAction,  metaTitle,  metaDescription,  focusKeyword,  relatedKeywords,  noIndex,  "product": product->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },  "products": products[]->{    _id,    name,    asin,    brand,    paApiPrimaryImageUrl,    paApiVariantImageUrls,    paApiImageUpdatedAt,    discoveryImage,    "category": category->{name, "slug": slug.current},    "latestScrapeImages": *[_type == "scrape" && product._ref == ^._id] | order(scrapedAt desc)[0].images  },  }
export type FeaturedPostsQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  _updatedAt: string;
  author: {
    firstName: string | null;
    lastName: string | null;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    preferredAiModel: null;
  } | null;
  postType: "comparison" | "general" | "productReview" | null;
  featured: boolean | null;
  affiliateDisclosure: string | null;
  callToAction: {
    text?: string;
    link?: string;
  } | null;
  metaTitle: string | null;
  metaDescription: string | null;
  focusKeyword: string | null;
  relatedKeywords: Array<string> | null;
  noIndex: boolean | null;
  product: {
    _id: string;
    name: string | null;
    asin: string | null;
    brand: string | null;
    paApiPrimaryImageUrl: null;
    paApiVariantImageUrls: null;
    paApiImageUpdatedAt: null;
    discoveryImage: string | null;
    category: {
      name: string | null;
      slug: string | null;
    } | null;
    latestScrapeImages: Array<string> | null;
  } | null;
  products: Array<{
    _id: string;
    name: string | null;
    asin: string | null;
    brand: string | null;
    paApiPrimaryImageUrl: null;
    paApiVariantImageUrls: null;
    paApiImageUpdatedAt: null;
    discoveryImage: string | null;
    category: {
      name: string | null;
      slug: string | null;
    } | null;
    latestScrapeImages: Array<string> | null;
  }> | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: pendingProductsQuery
// Query: *[_type == "product" && approvalStatus == "pending"] | order(_createdAt desc) {    _id,    name,    asin,    brand,    approvalStatus,    _createdAt,    "category": category->{name, slug}  }
export type PendingProductsQueryResult = Array<{
  _id: string;
  name: string | null;
  asin: string | null;
  brand: string | null;
  approvalStatus: "approved" | "paused" | "pending" | "rejected" | null;
  _createdAt: string;
  category: {
    name: string | null;
    slug: Slug | null;
  } | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: draftPostsQuery
// Query: *[_type == "post" && _id in path("drafts.**")] | order(_updatedAt desc) {    _id,    "title": coalesce(title, "Untitled"),    "slug": slug.current,    excerpt,    content,    postType,    _updatedAt,    "author": author->{firstName, lastName},    "product": product->{name, asin, discoveryImage},    "products": products[]->{name, asin, discoveryImage}  }
export type DraftPostsQueryResult = Array<{
  _id: string;
  title: string | "Untitled";
  slug: string | null;
  excerpt: string | null;
  content: BlockContent | null;
  postType: "comparison" | "general" | "productReview" | null;
  _updatedAt: string;
  author: {
    firstName: string | null;
    lastName: string | null;
  } | null;
  product: {
    name: string | null;
    asin: string | null;
    discoveryImage: string | null;
  } | null;
  products: Array<{
    name: string | null;
    asin: string | null;
    discoveryImage: string | null;
  }> | null;
}>;

// Source: lib/sanity/queries/theme.ts
// Variable: THEME_QUERY
// Query: *[_type == "theme" && defined(slug.current)] | order(_createdAt desc) {    _id,    _createdAt,    title,    "slug": slug.current,    primaryColor,    secondaryColor,    accentColor,    neutralColor,    headingFont,    bodyFont,    fontSize,    borderRadius,    spacing,    buttonStyle,    cardStyle,    navbarStyle,    description  }
export type THEME_QUERY_RESULT = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  primaryColor: Color | null;
  secondaryColor: Color | null;
  accentColor: Color | null;
  neutralColor: Color | null;
  headingFont: "Inter" | "Lora" | "Merriweather" | "Montserrat" | "Playfair Display" | "Roboto" | null;
  bodyFont: "Inter" | "Lora" | "Nunito Sans" | "Open Sans" | "Roboto" | "Source Sans Pro" | null;
  fontSize: {
    base?: "14px" | "16px" | "18px";
    scale?: number;
  } | null;
  borderRadius: "full" | "lg" | "md" | "none" | "sm" | "xl" | null;
  spacing: {
    containerWidth?: "1024px" | "1200px" | "1400px" | "1600px";
    sectionSpacing?: "1.5rem" | "2rem" | "3rem" | "4rem";
  } | null;
  buttonStyle: "pill" | "rounded" | "square" | null;
  cardStyle: "border" | "elevated" | "flat" | "shadow" | null;
  navbarStyle: "blur" | "solid" | "transparent" | null;
  description: string | null;
}>;

// Source: lib/sanity/queries/theme.ts
// Variable: THEME_BY_SLUG_QUERY
// Query: *[_type == "theme" && slug.current == $slug][0] {    _id,    _createdAt,    title,    "slug": slug.current,    primaryColor,    secondaryColor,    accentColor,    neutralColor,    headingFont,    bodyFont,    fontSize,    borderRadius,    spacing,    buttonStyle,    cardStyle,    navbarStyle,    description  }
export type THEME_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  primaryColor: Color | null;
  secondaryColor: Color | null;
  accentColor: Color | null;
  neutralColor: Color | null;
  headingFont: "Inter" | "Lora" | "Merriweather" | "Montserrat" | "Playfair Display" | "Roboto" | null;
  bodyFont: "Inter" | "Lora" | "Nunito Sans" | "Open Sans" | "Roboto" | "Source Sans Pro" | null;
  fontSize: {
    base?: "14px" | "16px" | "18px";
    scale?: number;
  } | null;
  borderRadius: "full" | "lg" | "md" | "none" | "sm" | "xl" | null;
  spacing: {
    containerWidth?: "1024px" | "1200px" | "1400px" | "1600px";
    sectionSpacing?: "1.5rem" | "2rem" | "3rem" | "4rem";
  } | null;
  buttonStyle: "pill" | "rounded" | "square" | null;
  cardStyle: "border" | "elevated" | "flat" | "shadow" | null;
  navbarStyle: "blur" | "solid" | "transparent" | null;
  description: string | null;
} | null;

// Source: lib/sanity/queries/theme.ts
// Variable: ACTIVE_THEME_QUERY
// Query: *[_type == "theme" && defined(slug.current)] | order(_createdAt desc)[0] {    _id,    _createdAt,    title,    "slug": slug.current,    primaryColor,    secondaryColor,    accentColor,    neutralColor,    headingFont,    bodyFont,    fontSize,    borderRadius,    spacing,    buttonStyle,    cardStyle,    navbarStyle,    description  }
export type ACTIVE_THEME_QUERY_RESULT = {
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  primaryColor: Color | null;
  secondaryColor: Color | null;
  accentColor: Color | null;
  neutralColor: Color | null;
  headingFont: "Inter" | "Lora" | "Merriweather" | "Montserrat" | "Playfair Display" | "Roboto" | null;
  bodyFont: "Inter" | "Lora" | "Nunito Sans" | "Open Sans" | "Roboto" | "Source Sans Pro" | null;
  fontSize: {
    base?: "14px" | "16px" | "18px";
    scale?: number;
  } | null;
  borderRadius: "full" | "lg" | "md" | "none" | "sm" | "xl" | null;
  spacing: {
    containerWidth?: "1024px" | "1200px" | "1400px" | "1600px";
    sectionSpacing?: "1.5rem" | "2rem" | "3rem" | "4rem";
  } | null;
  buttonStyle: "pill" | "rounded" | "square" | null;
  cardStyle: "border" | "elevated" | "flat" | "shadow" | null;
  navbarStyle: "blur" | "solid" | "transparent" | null;
  description: string | null;
} | null;

// Source: lib/sanity/queries/theme.ts
// Variable: THEME_PREVIEW_QUERY
// Query: *[_type == "theme" && defined(slug.current)] | order(_createdAt desc) {    _id,    title,    "slug": slug.current,    primaryColor,    headingFont,    buttonStyle  }
export type THEME_PREVIEW_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  primaryColor: Color | null;
  headingFont: "Inter" | "Lora" | "Merriweather" | "Montserrat" | "Playfair Display" | "Roboto" | null;
  buttonStyle: "pill" | "rounded" | "square" | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"settings\"][0]{\n  ...,\n  activeTheme->{\n    _id,\n    title,\n    slug,\n    primaryColor,\n    secondaryColor,\n    accentColor,\n    neutralColor,\n    headingFont,\n    bodyFont,\n    fontSize,\n    borderRadius,\n    spacing,\n    buttonStyle,\n    cardStyle,\n    navbarStyle,\n    description\n  },\n  affiliateDisclosure,\n  amazonAssociateTag,\n  ctaButtonText,\n  showPriceRange,\n  trustBadges,\n  twitterHandle,\n  googleVerification,\n  siteKeywords\n}": SettingsQueryResult;
    "*[_type == \"theme\" && slug.current == $slug][0]{\n  _id,\n  title,\n  slug,\n  primaryColor,\n  secondaryColor,\n  accentColor,\n  neutralColor,\n  headingFont,\n  bodyFont,\n  fontSize,\n  borderRadius,\n  spacing,\n  buttonStyle,\n  cardStyle,\n  navbarStyle,\n  description\n}": ThemeQueryResult;
    "\n  *[_type == 'page' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    \"pageBuilder\": pageBuilder[]{\n      ...,\n      _type == \"callToAction\" => {\n        \n  link {\n      ...,\n      \n  _type == \"link\" => {\n    \"page\": page->slug.current,\n    \"post\": post->slug.current\n  }\n\n      }\n,\n      },\n      _type == \"infoSection\" => {\n        content[]{\n          ...,\n          markDefs[]{\n            ...,\n            \n  _type == \"link\" => {\n    \"page\": page->slug.current,\n    \"post\": post->slug.current\n  }\n\n          }\n        }\n      },\n    },\n  }\n": GetPageQueryResult;
    "\n  *[_type == \"page\" || _type == \"post\" && defined(slug.current) || _type == \"category\" && defined(slug.current)] | order(_type asc) {\n    \"slug\": slug.current,\n    _type,\n    _updatedAt,\n    featured,\n    postType,\n  }\n": SitemapDataResult;
    "\n  *[_type == \"post\" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  excerpt,\n  coverImage,\n  \"date\": coalesce(date, _updatedAt),\n  _updatedAt,\n  \"author\": author->{\n    firstName,\n    lastName,\n    picture,\n    \"preferredAiModel\": preferredAiModel->{modelId, name}\n  },\n  postType,\n  featured,\n  affiliateDisclosure,\n  callToAction,\n  metaTitle,\n  metaDescription,\n  focusKeyword,\n  relatedKeywords,\n  noIndex,\n  \"product\": product->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n  \"products\": products[]->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n\n  }\n": AllPostsQueryResult;
    "\n  *[_type == \"post\" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  excerpt,\n  coverImage,\n  \"date\": coalesce(date, _updatedAt),\n  _updatedAt,\n  \"author\": author->{\n    firstName,\n    lastName,\n    picture,\n    \"preferredAiModel\": preferredAiModel->{modelId, name}\n  },\n  postType,\n  featured,\n  affiliateDisclosure,\n  callToAction,\n  metaTitle,\n  metaDescription,\n  focusKeyword,\n  relatedKeywords,\n  noIndex,\n  \"product\": product->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n  \"products\": products[]->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n\n  }\n": MorePostsQueryResult;
    "\n  *[_type == \"post\" && slug.current == $slug] [0] {\n    content[]{\n      ...,\n      _type == \"productImage\" => {\n        ...,\n        product->{\n          _id,\n          name,\n          asin,\n          paApiPrimaryImageUrl,\n          paApiVariantImageUrls,\n          paApiImageUpdatedAt,\n          discoveryImage,\n          \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n        }\n      },\n      markDefs[]{\n        ...,\n        \n  _type == \"link\" => {\n    \"page\": page->slug.current,\n    \"post\": post->slug.current\n  }\n\n      }\n    },\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  excerpt,\n  coverImage,\n  \"date\": coalesce(date, _updatedAt),\n  _updatedAt,\n  \"author\": author->{\n    firstName,\n    lastName,\n    picture,\n    \"preferredAiModel\": preferredAiModel->{modelId, name}\n  },\n  postType,\n  featured,\n  affiliateDisclosure,\n  callToAction,\n  metaTitle,\n  metaDescription,\n  focusKeyword,\n  relatedKeywords,\n  noIndex,\n  \"product\": product->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n  \"products\": products[]->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n\n  }\n": PostQueryResult;
    "\n  *[_type == \"post\" && defined(slug.current)]\n  {\"slug\": slug.current}\n": PostPagesSlugsResult;
    "\n  *[_type == \"page\" && defined(slug.current)]\n  {\"slug\": slug.current}\n": PagesSlugsResult;
    "\n  *[_type == \"product\" && asin == $asin][0] {\n    \n  _id,\n  name,\n  asin,\n  brand,\n  \"category\": category->{name, slug},\n  approvalStatus,\n  affiliateUrl\n\n  }\n": ProductByASINQueryResult;
    "\n  *[_type == \"product\" && category._ref == $categoryId] | order(_updatedAt desc) {\n    \n  _id,\n  name,\n  asin,\n  brand,\n  \"category\": category->{name, slug},\n  approvalStatus,\n  affiliateUrl\n\n  }\n": ProductsByCategoryQueryResult;
    "\n  *[_type == \"product\" && _id != $skip && category._ref == $categoryId] | order(_updatedAt desc) [0...$limit] {\n    \n  _id,\n  name,\n  asin,\n  brand,\n  \"category\": category->{name, slug},\n  approvalStatus,\n  affiliateUrl\n\n  }\n": RelatedProductsQueryResult;
    "\n  *[_type == \"category\"] | order(name asc) {\n    _id,\n    name,\n    \"slug\": slug.current,\n    description,\n    icon,\n    \"parentCategory\": parentCategory->{name, \"slug\": slug.current}\n  }\n": CategoriesQueryResult;
    "\n  *[_type == \"category\" && !defined(parentCategory)] | order(name asc) {\n    _id,\n    name,\n    \"slug\": slug.current,\n    description,\n    icon\n  }\n": BroadCategoriesQueryResult;
    "\n  *[_type == \"category\" && parentCategory->slug.current == $parentSlug] | order(name asc) {\n    _id,\n    name,\n    \"slug\": slug.current,\n    \"postCount\": count(*[_type == \"post\" && (\n      product->category._ref == ^._id ||\n      ^._id in products[]->category._ref\n    )])\n  }\n": SubcategoriesByParentQueryResult;
    "\n  *[_type == \"category\" && slug.current == $slug][0] {\n    _id,\n    name,\n    \"slug\": slug.current,\n    description,\n    metaDescription,\n    featuredImage,\n    icon,\n    \"parentCategory\": parentCategory->{name, \"slug\": slug.current},\n    \"isBroadCategory\": !defined(parentCategory),\n    \"posts\": *[_type == \"post\" && category._ref == ^._id && defined(slug.current)] | order(date desc) {\n      \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  excerpt,\n  coverImage,\n  \"date\": coalesce(date, _updatedAt),\n  _updatedAt,\n  \"author\": author->{\n    firstName,\n    lastName,\n    picture,\n    \"preferredAiModel\": preferredAiModel->{modelId, name}\n  },\n  postType,\n  featured,\n  affiliateDisclosure,\n  callToAction,\n  metaTitle,\n  metaDescription,\n  focusKeyword,\n  relatedKeywords,\n  noIndex,\n  \"product\": product->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n  \"products\": products[]->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n\n    }\n  }\n": CategoryBySlugQueryResult;
    "\n  *[_type == \"post\" && (\n    product->category->parentCategory->slug.current == $parentSlug ||\n    count(products[@->category->parentCategory->slug.current == $parentSlug]) > 0\n  ) && defined(slug.current)] | order(date desc) {\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  excerpt,\n  coverImage,\n  \"date\": coalesce(date, _updatedAt),\n  _updatedAt,\n  \"author\": author->{\n    firstName,\n    lastName,\n    picture,\n    \"preferredAiModel\": preferredAiModel->{modelId, name}\n  },\n  postType,\n  featured,\n  affiliateDisclosure,\n  callToAction,\n  metaTitle,\n  metaDescription,\n  focusKeyword,\n  relatedKeywords,\n  noIndex,\n  \"product\": product->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n  \"products\": products[]->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n\n  }\n": PostsByParentCategoryQueryResult;
    "\n  *[_type == \"category\" && defined(slug.current)]\n  {\"slug\": slug.current}\n": CategorySlugsQueryResult;
    "\n  *[_type == \"post\" && postType == \"productReview\" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  excerpt,\n  coverImage,\n  \"date\": coalesce(date, _updatedAt),\n  _updatedAt,\n  \"author\": author->{\n    firstName,\n    lastName,\n    picture,\n    \"preferredAiModel\": preferredAiModel->{modelId, name}\n  },\n  postType,\n  featured,\n  affiliateDisclosure,\n  callToAction,\n  metaTitle,\n  metaDescription,\n  focusKeyword,\n  relatedKeywords,\n  noIndex,\n  \"product\": product->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n  \"products\": products[]->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n\n  }\n": ProductReviewQueryResult;
    "\n  *[_type == \"post\" && postType == \"comparison\" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  excerpt,\n  coverImage,\n  \"date\": coalesce(date, _updatedAt),\n  _updatedAt,\n  \"author\": author->{\n    firstName,\n    lastName,\n    picture,\n    \"preferredAiModel\": preferredAiModel->{modelId, name}\n  },\n  postType,\n  featured,\n  affiliateDisclosure,\n  callToAction,\n  metaTitle,\n  metaDescription,\n  focusKeyword,\n  relatedKeywords,\n  noIndex,\n  \"product\": product->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n  \"products\": products[]->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n\n  }\n": ComparisonQueryResult;
    "\n  *[_type == \"post\" && featured == true && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  excerpt,\n  coverImage,\n  \"date\": coalesce(date, _updatedAt),\n  _updatedAt,\n  \"author\": author->{\n    firstName,\n    lastName,\n    picture,\n    \"preferredAiModel\": preferredAiModel->{modelId, name}\n  },\n  postType,\n  featured,\n  affiliateDisclosure,\n  callToAction,\n  metaTitle,\n  metaDescription,\n  focusKeyword,\n  relatedKeywords,\n  noIndex,\n  \"product\": product->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n  \"products\": products[]->{\n    _id,\n    name,\n    asin,\n    brand,\n    paApiPrimaryImageUrl,\n    paApiVariantImageUrls,\n    paApiImageUpdatedAt,\n    discoveryImage,\n    \"category\": category->{name, \"slug\": slug.current},\n    \"latestScrapeImages\": *[_type == \"scrape\" && product._ref == ^._id] | order(scrapedAt desc)[0].images\n  },\n\n  }\n": FeaturedPostsQueryResult;
    "\n  *[_type == \"product\" && approvalStatus == \"pending\"] | order(_createdAt desc) {\n    _id,\n    name,\n    asin,\n    brand,\n    approvalStatus,\n    _createdAt,\n    \"category\": category->{name, slug}\n  }\n": PendingProductsQueryResult;
    "\n  *[_type == \"post\" && _id in path(\"drafts.**\")] | order(_updatedAt desc) {\n    _id,\n    \"title\": coalesce(title, \"Untitled\"),\n    \"slug\": slug.current,\n    excerpt,\n    content,\n    postType,\n    _updatedAt,\n    \"author\": author->{firstName, lastName},\n    \"product\": product->{name, asin, discoveryImage},\n    \"products\": products[]->{name, asin, discoveryImage}\n  }\n": DraftPostsQueryResult;
    "\n  *[_type == \"theme\" && defined(slug.current)] | order(_createdAt desc) {\n    _id,\n    _createdAt,\n    title,\n    \"slug\": slug.current,\n    primaryColor,\n    secondaryColor,\n    accentColor,\n    neutralColor,\n    headingFont,\n    bodyFont,\n    fontSize,\n    borderRadius,\n    spacing,\n    buttonStyle,\n    cardStyle,\n    navbarStyle,\n    description\n  }\n": THEME_QUERY_RESULT;
    "\n  *[_type == \"theme\" && slug.current == $slug][0] {\n    _id,\n    _createdAt,\n    title,\n    \"slug\": slug.current,\n    primaryColor,\n    secondaryColor,\n    accentColor,\n    neutralColor,\n    headingFont,\n    bodyFont,\n    fontSize,\n    borderRadius,\n    spacing,\n    buttonStyle,\n    cardStyle,\n    navbarStyle,\n    description\n  }\n": THEME_BY_SLUG_QUERY_RESULT;
    "\n  *[_type == \"theme\" && defined(slug.current)] | order(_createdAt desc)[0] {\n    _id,\n    _createdAt,\n    title,\n    \"slug\": slug.current,\n    primaryColor,\n    secondaryColor,\n    accentColor,\n    neutralColor,\n    headingFont,\n    bodyFont,\n    fontSize,\n    borderRadius,\n    spacing,\n    buttonStyle,\n    cardStyle,\n    navbarStyle,\n    description\n  }\n": ACTIVE_THEME_QUERY_RESULT;
    "\n  *[_type == \"theme\" && defined(slug.current)] | order(_createdAt desc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    primaryColor,\n    headingFont,\n    buttonStyle\n  }\n": THEME_PREVIEW_QUERY_RESULT;
  }
}

